package HelloWorldApp;


/**
* HelloWorldApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloworldApp.idl
* dimanche 2 novembre 2025 19 h 14 WEST
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
